spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamSt3el/skillsync-config.git
          default-label: c-configs
          clone-on-start: true
server:
  port: 8888